export const GET_CART = "GET_CART"
export const UPDATE_CART = "UPDATE_CART"
export const ADD_CART = "ADD_CART"
export const DELETE_CART = "DELETE_CART"
export const INCREASE_QNT = "INCREASE_QNT"
export const DECREASE_QNT = "DECREASE_QNT"
